// public/vue/Button.vue
<script setup>
const props = defineProps({
  loading: Boolean,
  disabled: Boolean,
  text: String,
});
</script>

<template>
  <button
    :class="`Button text-base px-4 py-2 rounded transition text-white ${
      props.loading
        ? 'bg-slate-300 disabled:bg-slate-300 hover:bg-primary-400'
        : 'bg-primary-500'
    }`"
    :disabled="props.loading || props.disabled"
  >
    <slot v-if="props.loading" />
    <span v-else>{{ props.text }}</span>
  </button>
</template>

// components/Button.tsx
'use client';

import React from 'react';

interface ButtonProps {
  text?: string;
  loading?: boolean;
  onClick?: Function;
}

export default function Button(props: ButtonProps) {
  const { text, loading, onClick } = props;
  return (
    <button
      className="px-4 py-2 text-base text-white transition rounded Button bg-primary-500 hover:bg-primary-400 disabled:bg-slate-300"
      disabled={loading}
    >
      {loading}
      {!loading && text}
    </button>
  );
}
